# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alpha_beta_pruning_algorithm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from logic import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_alpha_beta_pruning_algorithm_window(object):
    def setupUi(self, alpha_beta_pruning_algorithm_window):
        alpha_beta_pruning_algorithm_window.setObjectName("alpha_beta_pruning_algorithm")
        alpha_beta_pruning_algorithm_window.resize(360, 136)

        self.verticalLayout = QtWidgets.QVBoxLayout(alpha_beta_pruning_algorithm_window)
        self.verticalLayout.setObjectName("verticalLayout")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.label = QtWidgets.QLabel(alpha_beta_pruning_algorithm_window)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)

        self.comboBox = QtWidgets.QComboBox(alpha_beta_pruning_algorithm_window)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label_2 = QtWidgets.QLabel(alpha_beta_pruning_algorithm_window)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)

        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.comboBox_2 = QtWidgets.QComboBox(alpha_beta_pruning_algorithm_window)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.buttonBox = QtWidgets.QDialogButtonBox(alpha_beta_pruning_algorithm_window)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(alpha_beta_pruning_algorithm_window)
        self.buttonBox.accepted.connect(alpha_beta_pruning_algorithm_window.accept) # type: ignore
        self.buttonBox.rejected.connect(alpha_beta_pruning_algorithm_window.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(alpha_beta_pruning_algorithm_window)

    def retranslateUi(self, alpha_beta_pruning_algorithm_window):
        _translate = QtCore.QCoreApplication.translate
        alpha_beta_pruning_algorithm_window.setWindowTitle(_translate("alpha_beta_pruning_algorithm", "Dialog"))
        self.label.setText(_translate("alpha_beta_pruning_algorithm", "Порядок анализа листьев дерева:"))
        self.comboBox.setItemText(0, _translate("alpha_beta_pruning_algorithm", "слева-направо"))
        self.comboBox.setItemText(1, _translate("alpha_beta_pruning_algorithm", "справа-налево"))
        self.label_2.setText(_translate("alpha_beta_pruning_algorithm", "Первый ход принадлежит игроку:"))
        self.comboBox_2.setItemText(0, _translate("alpha_beta_pruning_algorithm", "max"))
        self.comboBox_2.setItemText(1, _translate("alpha_beta_pruning_algorithm", "min"))

    def show_data(self):
        return self.comboBox.currentText(), self.comboBox_2.currentText()


def alpha_beta_pruning_algorithm_dialog():
    # global alpha_beta_pruning_algorithm
    alpha_beta_pruning_algorithm_window = QtWidgets.QDialog()
    ui = Ui_alpha_beta_pruning_algorithm_window()
    ui.setupUi(alpha_beta_pruning_algorithm_window)
    alpha_beta_pruning_algorithm_window.show()

    if alpha_beta_pruning_algorithm_window.exec():
        text_output.append(f"Порядок анализа листьев дерева: {ui.show_data()[0]}\n")
        text_output.append(f"Первый ход принадлжет игроку: {ui.show_data()[1]}\n")
        text_output.append("\nВывод протокола:\n")

        if ui.show_data()[0] == "слева-направо" and ui.show_data()[1] == "max":
            alpha_beta_pruning(trees_dict[current_tree_var.get()], "1", 4, -inf, +inf, False, True)
        elif ui.show_data()[0] == "слева-направо" and ui.show_data()[1] == "min":
            alpha_beta_pruning(trees_dict[current_tree_var.get()], "1", 4, -inf, +inf, False, False)
        elif ui.show_data()[0] == "справа-налево" and ui.show_data()[1] == "max":
            alpha_beta_pruning(trees_dict[current_tree_var.get()], "1", 4, -inf, +inf, True, True)
        elif ui.show_data()[0] == "справа-налево" and ui.show_data()[1] == "min":
            alpha_beta_pruning(trees_dict[current_tree_var.get()], "1", 4, -inf, +inf, True, False)