# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import matplotlib.pyplot as plt

from logic import *
from minimax_algorithm import *
from alpha_beta_pruning_algorithm import *

from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)

        self.minimax_algorithm_button = QtWidgets.QPushButton(self.centralwidget)
        self.minimax_algorithm_button.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.minimax_algorithm_button)

        self.alpha_beta_pruning_algorithm_button = QtWidgets.QPushButton(self.centralwidget)
        self.alpha_beta_pruning_algorithm_button.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.alpha_beta_pruning_algorithm_button)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.horizontalLayout.addLayout(self.verticalLayout)

        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)

        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)
        self.verticalLayout_2.addWidget(self.canvas)

        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)

        self.text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.text_edit.setObjectName("text_output")
        self.verticalLayout_2.addWidget(self.text_edit)

        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.plot_canvas()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ЛР №3 ПЗвИС"))
        self.label.setText(_translate("MainWindow", "НАСТРОЙКИ"))
        self.pushButton.setText(_translate("MainWindow", "Выбор игрового дерева"))
        self.pushButton_2.setText(_translate("MainWindow", "Задать оценки листьев"))
        self.minimax_algorithm_button.setText(_translate("MainWindow", "Минимаксный алгоритм"))
        self.alpha_beta_pruning_algorithm_button.setText(_translate("MainWindow", "Алгоритм с отсечениями"))
        self.text_edit.setText(_translate("MainWindow", "Программа запущена.\n"
                                                        "По умолчанию строится игровое дерево №1: " + str(G) +
                                                        ".\nВнизу каждой вершины отображается ее порядковый номер,  а в самой вершине ее значение."))

        self.minimax_algorithm_button.clicked.connect(minimax_algorithm_dialog)
        self.alpha_beta_pruning_algorithm_button.clicked.connect(alpha_beta_pruning_algorithm_dialog)

        self.minimax_algorithm_button.clicked.connect(self.plot_canvas)
        self.alpha_beta_pruning_algorithm_button.clicked.connect(self.plot_canvas)

        self.minimax_algorithm_button.clicked.connect(self.protocol_update)
        self.alpha_beta_pruning_algorithm_button.clicked.connect(self.protocol_update)

    def plot_canvas(self):
        self.figure.clear()
        draw_tree()
        self.canvas.draw()

    def protocol_update(self):
        self.text_edit.clear()
        self.text_edit.append(str("".join(text_output)))
        text_output.clear()