# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tree_variation_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from logic import *
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tree_variation_selection_window(object):
    def setupUi(self, tree_variation_selection_window):
        tree_variation_selection_window.setObjectName("tree_variation_selection_window")
        tree_variation_selection_window.resize(376, 100)

        self.verticalLayout = QtWidgets.QVBoxLayout(tree_variation_selection_window)
        self.verticalLayout.setObjectName("verticalLayout")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label = QtWidgets.QLabel(tree_variation_selection_window)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.comboBox = QtWidgets.QComboBox(tree_variation_selection_window)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(list(trees_dict.keys()))
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.buttonBox = QtWidgets.QDialogButtonBox(tree_variation_selection_window)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(tree_variation_selection_window)
        self.buttonBox.accepted.connect(tree_variation_selection_window.accept) # type: ignore
        self.buttonBox.rejected.connect(tree_variation_selection_window.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(tree_variation_selection_window)

    def retranslateUi(self, tree_variation_selection_window):
        _translate = QtCore.QCoreApplication.translate
        tree_variation_selection_window.setWindowTitle(_translate("tree_variation_selection", "Выбор варианта"))
        self.label.setText(_translate("tree_variation_selection", "Выберите вариант игрового дерева:"))

    def show_data(self):
        return self.comboBox.currentText()


def tree_variation_selection_dialog():
    # global tree_variation_selection
    tree_variation_selection_window = QtWidgets.QDialog()
    ui = Ui_tree_variation_selection_window()
    ui.setupUi(tree_variation_selection_window)
    tree_variation_selection_window.show()

    if tree_variation_selection_window.exec():
        current_tree_var.change(ui.show_data())
        text_output.append(f"Выбрано игровое дерево №{ui.show_data()}")